name: Run Python Script Every Minute

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  execute-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Specify the Python version

    - name: Install dependencies
      run: pip install -r requirements.txt # If you have a requirements.txt file

    - name: Run the script
      run: python "monday automation.py" # Use quotes if the script name contains spaces
